#!/usr/bin/env sh

set -x

. "$(dirname "$0")/versions"

if [ "${DO_NOTHING}" = "true" ]; then
    echo "Not doing anything because DO_NOTHING flag is set to true"
    exit 0
fi

prepare()
{
    if [ "${DOCKER_ARCH}x" = "x" ] || [ "${DOCKER_ARCH}" = "amd64" ]; then
        sed \
            -e "s/__DOCKER_ARCH__/amd64/g" \
            -e "/__QEMU_ARCH__/d" \
            "${DOCKERFILE_PATH}" > "${DOCKERFILE_PATH}.${DOCKER_ARCH}"
    else
        QEMU_USER_STATIC_DOWNLOAD_URL="https://github.com/multiarch/qemu-user-static/releases/download"
        QEMU_USER_STATIC_LATEST_TAG=$(curl -sL https://api.github.com/repos/multiarch/qemu-user-static/tags \
            | grep 'name.*v[0-9]' \
            | head -n 1 \
            | cut -d '"' -f 4)

        curl -sL "${QEMU_USER_STATIC_DOWNLOAD_URL}/${QEMU_USER_STATIC_LATEST_TAG}/x86_64_qemu-${QEMU_ARCH}-static.tar.gz" \
            | tar xzv

        sed \
            -e "s/__DOCKER_ARCH__/${DOCKER_ARCH}/g" \
            -e "s/__QEMU_ARCH__/${QEMU_ARCH}/g" \
            "${DOCKERFILE_PATH}" > "${DOCKERFILE_PATH}.${DOCKER_ARCH}"

        docker run --rm --privileged multiarch/qemu-user-static:register --reset
    fi
}

build_static()
{
    docker build \
        --file "${DOCKERFILE_PATH}.${DOCKER_ARCH}" \
        --build-arg aria_version="${ARIA_VERSION}" \
        --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
        --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
        --build-arg BUILD_VERSION="${LABEL_VERSION}" \
        --target static \
        "$@" \
        .
}

build_embed()
{
    docker build \
        --file "${DOCKERFILE_PATH}.${DOCKER_ARCH}" \
        --build-arg aria_version="${ARIA_VERSION}" \
        --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
        --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
        --build-arg BUILD_VERSION="${LABEL_VERSION}" \
        --target embedded \
        "$@" \
        .
}

case "${DOCKER_TAG}" in
    'latest')
        ARIA_VERSION="tags/release-${ARIA2_REF_VERSION}.0"
        DOCKER_ARCH='amd64'
        LABEL_VERSION="${ARIA2_REF_VERSION}-rc${ARIA2_IMAGE_VERSION}"
        prepare
        build_static --tag "${DOCKER_REPO}:${DOCKER_TAG}" --tag "${DOCKER_REPO}:${ARIA2_REF_VERSION}"
        build_embed --tag "${DOCKER_REPO}:busybox" --tag "${DOCKER_REPO}:${ARIA2_REF_VERSION}-busybox"
        ;;
    'latest-arm32v6')
        ARIA_VERSION="tags/release-${ARIA2_REF_VERSION}.0"
        DOCKER_ARCH='arm32v6'
        QEMU_ARCH='arm'
        LABEL_VERSION="${ARIA2_REF_VERSION}-rc${ARIA2_IMAGE_VERSION}"
        prepare
        build_static --tag "${DOCKER_REPO}:${DOCKER_TAG}" --tag "${DOCKER_REPO}:${ARIA2_REF_VERSION}-arm32v6"
        build_embed --tag "${DOCKER_REPO}:busybox-arm32v6" --tag "${DOCKER_REPO}:${ARIA2_REF_VERSION}-busybox-arm32v6"
        ;;
    'latest-arm32v7')
        ARIA_VERSION="tags/release-${ARIA2_REF_VERSION}.0"
        DOCKER_ARCH='arm32v7'
        QEMU_ARCH='arm'
        LABEL_VERSION="${ARIA2_REF_VERSION}-rc${ARIA2_IMAGE_VERSION}"
        prepare
        build_static --tag "${DOCKER_REPO}:${DOCKER_TAG}" --tag "${DOCKER_REPO}:${ARIA2_REF_VERSION}-arm32v7"
        build_embed --tag "${DOCKER_REPO}:busybox-arm32v7" --tag "${DOCKER_REPO}:${ARIA2_REF_VERSION}-busybox-arm32v7"
        ;;
     'latest-arm64v8')
        ARIA_VERSION="tags/release-${ARIA2_REF_VERSION}.0"
        DOCKER_ARCH='arm64v8'
        QEMU_ARCH='aarch64'
        LABEL_VERSION="${ARIA2_REF_VERSION}-rc${ARIA2_IMAGE_VERSION}"
        prepare
        build_static --tag "${DOCKER_REPO}:${DOCKER_TAG}" --tag "${DOCKER_REPO}:${ARIA2_REF_VERSION}-arm64v8"
        build_embed --tag "${DOCKER_REPO}:busybox-arm64v8" --tag "${DOCKER_REPO}:${ARIA2_REF_VERSION}-busybox-arm64v8"
        ;;
     'edge')
        ARIA_VERSION='master'
        DOCKER_ARCH='amd64'
        LABEL_VERSION="$(git ls-remote https://github.com/aria2/aria2 "${ARIA_VERSION}" | head -1 | cut -f1)-rc${ARIA2_IMAGE_VERSION}"
        prepare
        build_static --tag "${DOCKER_REPO}:${DOCKER_TAG}"
        build_embed --tag "${DOCKER_REPO}:edge-busybox"
        ;;
    'edge-arm32v6')
        ARIA_VERSION='master'
        DOCKER_ARCH='arm32v6'
        QEMU_ARCH='arm'
        LABEL_VERSION="$(git ls-remote https://github.com/aria2/aria2 "${ARIA_VERSION}" | head -1 | cut -f1)-rc${ARIA2_IMAGE_VERSION}"
        prepare
        build_static --tag "${DOCKER_REPO}:${DOCKER_TAG}"
        build_embed --tag "${DOCKER_REPO}:edge-busybox-arm32v6"
        ;;
    'edge-arm32v7')
        ARIA_VERSION='master'
        DOCKER_ARCH='arm32v7'
        QEMU_ARCH='arm'
        LABEL_VERSION="$(git ls-remote https://github.com/aria2/aria2 "${ARIA_VERSION}" | head -1 | cut -f1)-rc${ARIA2_IMAGE_VERSION}"
        prepare
        build_static --tag "${DOCKER_REPO}:${DOCKER_TAG}"
        build_embed --tag "${DOCKER_REPO}:edge-busybox-arm32v7"
        ;;
    'edge-arm64v8')
        ARIA_VERSION='master'
        DOCKER_ARCH='arm64v8'
        QEMU_ARCH='aarch64'
        LABEL_VERSION="$(git ls-remote https://github.com/aria2/aria2 "${ARIA_VERSION}" | head -1 | cut -f1)-rc${ARIA2_IMAGE_VERSION}"
        prepare
        build_static --tag "${DOCKER_REPO}:${DOCKER_TAG}"
        build_embed --tag "${DOCKER_REPO}:edge-busybox-arm64v8"
        ;;
    *)
        echo "Unsupported Docker Tag : ${DOCKER_TAG}"
        exit 1
        ;;
esac

