#!/usr/bin/env sh

BUILD_ARCH=$(echo "${DOCKERFILE_PATH}" | cut -d '.' -f 2)

[ "${BUILD_ARCH}" = 'Dockerfile' ] && \
    { echo 'qemu-user-static: Download not required for current arch'; exit 0; }

case "${BUILD_ARCH}" in
    'arm32v6'|'arm32v7')
        QEMU_USER_STATIC_ARCH='arm';;
    *)
        echo "unsupported architecture: ${BUILD_ARCH}"
        exit 1
        ;;
esac

QEMU_USER_STATIC_DOWNLOAD_URL="https://github.com/multiarch/qemu-user-static/releases/download"
QEMU_USER_STATIC_LATEST_TAG=$(wget -O- https://api.github.com/repos/multiarch/qemu-user-static/tags \
    | grep 'name.*v[0-9]' \
    | head -n 1 \
    | cut -d '"' -f 4)

wget -O- "${QEMU_USER_STATIC_DOWNLOAD_URL}/${QEMU_USER_STATIC_LATEST_TAG}/x86_64_qemu-${QEMU_USER_STATIC_ARCH}-static.tar.gz" \
    | tar xzv
