#!/usr/bin/env sh

for arch in amd64 arm32v6 arm32v7 arm64v8; do
    docker push "${IMAGE_NAME}-${arch}"
done;

docker manifest create "${IMAGE_NAME}" "${IMAGE_NAME}-amd64" "${IMAGE_NAME}-arm32v6" "${IMAGE_NAME}-arm32v7" "${IMAGE_NAME}-arm32v8"
docker manifest annotate "${IMAGE_NAME}" "${IMAGE_NAME}-amd64" --os linux --arch amd64
docker manifest annotate "${IMAGE_NAME}" "${IMAGE_NAME}-arm32v6" --os linux --arch arm --variant armv6
docker manifest annotate "${IMAGE_NAME}" "${IMAGE_NAME}-arm32v7" --os linux --arch arm --variant armv7
docker manifest annotate "${IMAGE_NAME}" "${IMAGE_NAME}-arm32v8" --os linux --arch arm64 --variant armv8
docker manifest push "${IMAGE_NAME}"
