#!/usr/bin/env sh

set -x

source "$(dirname "$0")/versions"

docker push "${DOCKER_REPO}:${DOCKER_TAG}"

case "${DOCKER_TAG}" in
    'latest') docker push "${DOCKER_REPO}:busybox" && docker push "${DOCKER_REPO}:${ARIA2_REF_VERSION}" && docker push "${DOCKER_REPO}:${ARIA2_REF_VERSION}-busybox";;
    'latest-arm32v6') docker push "${DOCKER_REPO}:busybox-arm32v6" && docker push "${DOCKER_REPO}:${ARIA2_REF_VERSION}-arm32v6" && docker push "${DOCKER_REPO}:${ARIA2_REF_VERSION}-busybox-arm32v6";;
    'latest-arm32v7') docker push "${DOCKER_REPO}:busybox-arm32v7" && docker push "${DOCKER_REPO}:${ARIA2_REF_VERSION}-arm32v7" && docker push "${DOCKER_REPO}:${ARIA2_REF_VERSION}-busybox-arm32v7";;
    'latest-arm64v8') docker push "${DOCKER_REPO}:busybox-arm64v8" && docker push "${DOCKER_REPO}:${ARIA2_REF_VERSION}-arm64v8" && docker push "${DOCKER_REPO}:${ARIA2_REF_VERSION}-busybox-arm64v8";;
    'edge') docker push "${DOCKER_REPO}:edge-busybox" ;;
    'edge-arm32v6') docker push "${DOCKER_REPO}:edge-busybox-arm32v6" ;;
    'edge-arm32v7') docker push "${DOCKER_REPO}:edge-busybox-arm32v7" ;;
    'edge-arm64v8') docker push "${DOCKER_REPO}:edge-busybox-arm64v8" ;;
    *) echo "Unknown Docker Tag: ${DOCKER_TAG}" && exit 1;;
esac

