#!/usr/bin/env sh

set -x

docker push "${DOCKER_REPO}:${DOCKER_TAG}"

case "${DOCKER_TAG}" in
    'latest') docker push "${DOCKER_REPO}:busybox" && docker push "${DOCKER_REPO}:1.34" && docker push "${DOCKER_REPO}:1.34-busybox";;
    'latest-arm32v6') docker push "${DOCKER_REPO}:busybox-arm32v6" && docker push "${DOCKER_REPO}:1.34-arm32v6" && docker push "${DOCKER_REPO}:1.34-busybox-arm32v6";;
    'latest-arm32v7') docker push "${DOCKER_REPO}:busybox-arm32v7" && docker push "${DOCKER_REPO}:1.34-arm32v7" && docker push "${DOCKER_REPO}:1.34-busybox-arm32v7";;
    'latest-arm64v8') docker push "${DOCKER_REPO}:busybox-arm64v8" && docker push "${DOCKER_REPO}:1.34-arm64v8" && docker push "${DOCKER_REPO}:1.34-busybox-arm64v8";;
    'edge') docker push "${DOCKER_REPO}:edge-busybox" ;;
    'edge-arm32v6') docker push "${DOCKER_REPO}:edge-busybox-arm32v6" ;;
    'edge-arm32v7') docker push "${DOCKER_REPO}:edge-busybox-arm32v7" ;;
    'edge-arm64v8') docker push "${DOCKER_REPO}:edge-busybox-arm64v7" ;;
    *) echo "Unknown Docker Tag: ${DOCKER_TAG}" && exit 1;;
esac

#case "${DOCKER_TAG}" in
#    'latest'*) DOCKER_MANIFEST="${DOCKER_REPO}:latest ${DOCKER_REPO}:1.34 ${DOCKER_REPO}:busybox ${DOCKER_REPO}:1.34-busybox";;
#    'edge'*) DOCKER_MANIFEST="${DOCKER_REPO}:edge ${DOCKER_REPO}:edge-busybox";;
#esac

#for manifest in ${DOCKER_MANIFEST}; do
#
#    docker manifest create "${manifest}" "${manifest}" "${manifest}-arm32v6" "${manifest}-arm32v7" "${manifest}-arm32v8"
#    docker manifest annotate "${manifest}" "${manifest}" --os linux --arch amd64
#    docker manifest annotate "${manifest}" "${manifest}-arm32v6" --os linux --arch arm --variant armv6
#    docker manifest annotate "${manifest}" "${manifest}-arm32v7" --os linux --arch arm --variant armv7
#    docker manifest annotate "${manifest}" "${manifest}-arm64v8" --os linux --arch arm64 --variant armv8
#    docker manifest push "${manifest}"
#
#done

