#!/usr/bin/env sh

set -x

. "$(dirname "$0")/../../scripts/global_functions.sh"

if [ "${DO_NOTHING}" = "true" ]; then
    echo "Not doing anything because DO_NOTHING flag is set to true"
    exit 0
fi

qemu_test "${DOCKER_REPO}:${DOCKER_TAG}" "https://www.google.com" || exit 1

case "${DOCKER_TAG}" in
    latest)
        qemu_test "${DOCKER_REPO}:busybox" "https://www.google.com"
    ;;
    latest-*)
        qemu_test "${DOCKER_REPO}:busybox-${DOCKER_ARCH}" "https://www.google.com"
    ;;
    edge)
        qemu_test "${DOCKER_REPO}:edge-busybox" "https://www.google.com"
    ;;
    edge-*)
        qemu_test "${DOCKER_REPO}:edge-busybox-${DOCKER_ARCH}" "https://www.google.com"
    ;;
    *)
        echo "No tests to run for DOCKER_TAG:${DOCKER_TAG}" && \
        exit 1
    ;;
esac

