version: 2

jobs:
  aria2-executor-default: &aria2-executor-defaults
    machine: true
    working_directory: ~/

  aria2-defaults:
    environment: &aria2-env
      DOCKERFILE_PATH: Dockerfile
      DOCKER_REPO: leodagan/aria2
    steps:
      - attach_workspace: &aria2-attach-workspace
          at: ~/
      - persist_to_workspace: &aria2-persist-workspace
          root: ~/
          paths:
            - aria2
      - run: &aria2-build-command cd ~/aria2 && ./hooks/build
      - run: &aria2-save-command cd ~/aria2 && docker save -o "aria2-${DOCKER_TAG}.tar" "${DOCKER_REPO}:${DOCKER_TAG}"
      - run: &aria2-load-command cd ~/aria2 && docker load < "aria2-${DOCKER_TAG}.tar"
      - run: &aria2-test-command cd ~/aria2 && ./hooks/test

        
  aria2-build-latest-amd64:
    <<: *aria2-executor-defaults
    steps:
      - *aria2-attach-workspace
      - checkout
      - run:
          name: aria2 amd64
          command: *aria2-build-command
          environment: &aria2-env-amd64
            <<: *aria2-env
            DOCKER_TAG: latest
      - run:
          command: *aria2-save-command
          environment:
            <<: *aria2-env-amd64
      - run:
          command: cd ~/aria2 && docker save -o "busybox.tar" "${DOCKER_REPO}:busybox"
          environment:
            <<: *aria2-env-amd64
      - *aria2-persist-workspace

  aria2-test-latest-amd64:
    <<: *aria2-executor-defaults
    steps:
      - *aria2-attach-workspace
      - run:
          command: *aria2-load-command
          environment:
            <<: *aria2-env-amd64
      - run:
          command: cd ~/aria2 && docker load < "busybox.tar"
          environment:
            <<: *aria2-env-amd64
      - run:
          name: test aria2 amd64
          command: *aria2-test-command
          environment:
            <<: *aria2-env-amd64
workflows:
  version: 2
  aria2-latest:
    jobs:
      - aria2-build-latest-amd64
      - aria2-test-latest-amd64:
          requires:
            - aria2-build-latest-amd64
