aria2-matrix:
  executor: &aria2-executor-defaults
    machine: true
    working_directory: ~/docker
  environment: &aria2-env
    DOCKERFILE_PATH: Dockerfile
    DOCKER_REPO: leodagan/aria2
  attach_step: &aria2-attach-workspace
    attach_workspace:
      at: ~/
  persist_step: &aria2-persist-workspace
    persist_to_workspace:
      root: ~/
      paths:
        - docker

  build-cmd: &aria2-build-command |
    cd aria2
    ./hooks/build
  test-cmd: &aria2-test-command |
    cd aria2
    ./hooks/test

  amd64:
    env: &aria2-env-amd64
      <<: *aria2-env
      DOCKER_TAG: latest
      EMBED_TAG: busybox
    build: &aria2-build-amd64
      run:
        command: *aria2-build-command
        environment:
          <<: *aria2-env-amd64
    test: &aria2-test-amd64
      run:
        command: *aria2-test-command
        environment:
          <<: *aria2-env-amd64

  arm32v7:
    env: &aria2-env-arm32v7
      <<: *aria2-env
      DOCKER_TAG: latest-arm32v7
      EMBED_TAG: busybox-arm32v7
    build: &aria2-build-arm32v7
      run:
        command: *aria2-build-command
        environment:
          <<: *aria2-env-arm32v7
    test: &aria2-test-arm32v7
      run:
        command: *aria2-test-command
        environment:
          <<: *aria2-env-arm32v7

version: 2

jobs:
  docker-checkout:
    <<: *aria2-executor-defaults
    steps:
      - *aria2-attach-workspace
      - checkout
      - *aria2-persist-workspace

  aria2-build-latest-amd64:
    <<: *aria2-executor-defaults
    steps:
      - *aria2-attach-workspace
      - *aria2-build-amd64
      - *aria2-test-amd64

  aria2-build-latest-arm32v7:
    <<: *aria2-executor-defaults
    steps:
      - *aria2-attach-workspace
      - *aria2-build-arm32v7
      - *aria2-test-arm32v7

workflows:
  version: 2
  aria2-latest:
    jobs:
      - docker-checkout
      - aria2-build-latest-amd64:
          requires:
            - docker-checkout
      - aria2-build-latest-arm32v7:
          requires:
            - docker-checkout

