docker-images-matrix:
  executor: &images-executor-defaults
    machine: true
    working_directory: ~/docker
  attach_step: &images-attach-workspace
    attach_workspace:
      at: ~/
  persist_step: &images-persist-workspace
    persist_to_workspace:
      root: ~/
      paths:
        - docker
  master-workflow: &images-master-workflow
    filters:
      branches:
        only: master
    requires:
      - docker-checkout
  publish-workflow: &images-publish-workflow
    filters:
      branches:
        only: master

version: 2.1

executors:
  ariang:
    <<: *images-executor-defaults
    environment:
      PROJECT_PATH: ariang
      DOCKERFILE_PATH: Dockerfile
      DOCKER_REPO: leodagan/ariang
  aria2:
    <<: *images-executor-defaults
    environment:
      PROJECT_PATH: aria2
      DOCKERFILE_PATH: Dockerfile
      DOCKER_REPO: leodagan/aria2
  pptp:
    <<: *images-executor-defaults
    environment:
      PROJECT_PATH: pptp
      DOCKERFILE_PATH: Dockerfile
      DOCKER_REPO: leodagan/pptp
  filebrowser:
    <<: *images-executor-defaults
    environment:
      PROJECT_PATH: filebrowser
      DOCKERFILE_PATH: Dockerfile
      DOCKER_REPO: leodagan/filebrowser
  pptpd:
    <<: *images-executor-defaults
    environment:
      PROJECT_PATH: pptpd
      DOCKERFILE_PATH: Dockerfile
      DOCKER_REPO: leodagan/pptpd
  butterfly:
    <<: *images-executor-defaults
    environment:
      PROJECT_PATH: butterfly
      DOCKERFILE_PATH: Dockerfile
      DOCKER_REPO: leodagan/butterfly

jobs:
  docker-checkout:
    parameters:
      runner:
        type: executor
    executor: << parameters.runner >>
    steps:
      - *images-attach-workspace
      - checkout
      - run: |
          if [ "$(git --no-pager log -1 --format=format:%H --full-diff "${PROJECT_PATH}")" != "${CIRCLE_SHA1}"  ]; then
            echo "No changes in ${PROJECT_PATH} repository, skipping step..."
            circleci-agent step halt
          fi
      - *images-persist-workspace

  docker-build:
    parameters:
      docker-tag:
        type: string
      runner:
        type: executor
    executor: << parameters.runner >>
    steps:
      - *images-attach-workspace
      - run: |
          if [ ! -e "${PROJECT_PATH}" ]; then circleci-agent step halt; fi
      - run: |
          cd "${PROJECT_PATH}"
          ./hooks/build
      - run: |
          cd "${PROJECT_PATH}"
          ./hooks/test
      - run: |
          cd "${PROJECT_PATH}"
          echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USERNAME" --password-stdin
          ./hooks/push
    environment:
      DOCKER_TAG: << parameters.docker-tag >>

  docker-publish:
    parameters:
      badge-hook:
        type: string
      runner:
        type: executor
    executor: << parameters.runner >>
    steps:
      - *images-attach-workspace
      - run: |
          if [ ! -e "${PROJECT_PATH}" ]; then circleci-agent step halt; fi
      - run: curl -X POST '<< parameters.badge-hook >>'

workflows:
  pptp:
    jobs:
      - docker-checkout:
          runner: pptp
      - docker-build:
          runner: pptp
          docker-tag: &tag latest
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: pptp
          docker-tag: &tag latest-arm32v6
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: pptp
          docker-tag: &tag latest-arm32v7
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: pptp
          docker-tag: &tag latest-arm64v8
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: pptp
          docker-tag: &tag edge
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: pptp
          docker-tag: &tag edge-arm32v6
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: pptp
          docker-tag: &tag edge-arm32v7
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: pptp
          docker-tag: &tag edge-arm64v8
          name: *tag
          <<: *images-master-workflow
      - docker-publish:
          runner: ariang
          badge-hook: https://hooks.microbadger.com/images/leodagan/pptp/Oaje7NSXWyvxNuW--LAn11_gqoE=
          <<: *images-publish-workflow
          requires:
            - latest
            - latest-arm32v6
            - latest-arm32v7
            - latest-arm64v8
            - edge
            - edge-arm32v6
            - edge-arm32v7
            - edge-arm64v8
  ariang:
    jobs:
      - docker-checkout:
          runner: ariang
      - docker-build:
          runner: ariang
          docker-tag: &tag latest
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: ariang
          docker-tag: &tag latest-arm32v6
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: ariang
          docker-tag: &tag latest-arm32v7
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: ariang
          docker-tag: &tag latest-arm64v8
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: ariang
          docker-tag: &tag edge
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: ariang
          docker-tag: &tag edge-arm32v6
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: ariang
          docker-tag: &tag edge-arm32v7
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: ariang
          docker-tag: &tag edge-arm64v8
          name: *tag
          <<: *images-master-workflow
      - docker-publish:
          runner: ariang
          badge-hook: https://hooks.microbadger.com/images/leodagan/ariang/xcN8593pqjchKNuVtW7oCgFdebU=
          <<: *images-publish-workflow
          requires:
            - latest
            - latest-arm32v6
            - latest-arm32v7
            - latest-arm64v8
            - edge
            - edge-arm32v6
            - edge-arm32v7
            - edge-arm64v8

  aria2:
    jobs:
      - docker-checkout:
          runner: aria2
      - docker-build:
          runner: aria2
          docker-tag: &tag latest
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: aria2
          docker-tag: &tag latest-arm32v6
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: aria2
          docker-tag: &tag latest-arm32v7
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: aria2
          docker-tag: &tag latest-arm64v8
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: aria2
          docker-tag: &tag edge
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: aria2
          docker-tag: &tag edge-arm32v6
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: aria2
          docker-tag: &tag edge-arm32v7
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: aria2
          docker-tag: &tag edge-arm64v8
          name: *tag
          <<: *images-master-workflow
      - docker-publish:
          runner: aria2
          badge-hook: https://hooks.microbadger.com/images/leodagan/aria2/iUEnHO2bAU5Nk48i4D6VpzzOlMQ=
          <<: *images-publish-workflow
          requires:
            - latest
            - latest-arm32v6
            - latest-arm32v7
            - latest-arm64v8
            - edge
            - edge-arm32v6
            - edge-arm32v7
            - edge-arm64v8

  filebrowser:
    jobs:
      - docker-checkout:
          runner: filebrowser
      - docker-build:
          runner: filebrowser
          docker-tag: &tag latest
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: filebrowser
          docker-tag: &tag latest-arm32v6
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: filebrowser
          docker-tag: &tag latest-arm32v7
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: filebrowser
          docker-tag: &tag latest-arm64v8
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: filebrowser
          docker-tag: &tag edge
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: filebrowser
          docker-tag: &tag edge-arm32v6
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: filebrowser
          docker-tag: &tag edge-arm32v7
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: filebrowser
          docker-tag: &tag edge-arm64v8
          name: *tag
          <<: *images-master-workflow
      - docker-publish:
          runner: filebrowser
          badge-hook: https://hooks.microbadger.com/images/leodagan/filebrowser/V6iiRGpsD1WJnPN-jDRwx3UQ3Hg=
          <<: *images-publish-workflow
          requires:
            - latest
            - latest-arm32v6
            - latest-arm32v7
            - latest-arm64v8
            - edge
            - edge-arm32v6
            - edge-arm32v7
            - edge-arm64v8

  pptpd:
    jobs:
      - docker-checkout:
          runner: pptpd
      - docker-build:
          runner: pptpd
          docker-tag: &tag latest
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: pptpd
          docker-tag: &tag latest-arm32v6
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: pptpd
          docker-tag: &tag latest-arm32v7
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: pptpd
          docker-tag: &tag latest-arm64v8
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: pptpd
          docker-tag: &tag edge
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: pptpd
          docker-tag: &tag edge-arm32v6
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: pptpd
          docker-tag: &tag edge-arm32v7
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: pptpd
          docker-tag: &tag edge-arm64v8
          name: *tag
          <<: *images-master-workflow
      - docker-publish:
          runner: pptpd
          badge-hook: https://hooks.microbadger.com/images/leodagan/pptpd/-n5gjUFsWLTbkxGYd3qFCkYxbA4=
          <<: *images-publish-workflow
          requires:
            - latest
            - latest-arm32v6
            - latest-arm32v7
            - latest-arm64v8
            - edge
            - edge-arm32v6
            - edge-arm32v7
            - edge-arm64v8

  butterfly:
    jobs:
      - docker-checkout:
          runner: butterfly
      - docker-build:
          runner: butterfly
          docker-tag: &tag latest
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: butterfly
          docker-tag: &tag latest-arm32v6
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: butterfly
          docker-tag: &tag latest-arm32v7
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: butterfly
          docker-tag: &tag latest-arm64v8
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: butterfly
          docker-tag: &tag edge
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: butterfly
          docker-tag: &tag edge-arm32v6
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: butterfly
          docker-tag: &tag edge-arm32v7
          name: *tag
          <<: *images-master-workflow
      - docker-build:
          runner: butterfly
          docker-tag: &tag edge-arm64v8
          name: *tag
          <<: *images-master-workflow
      - docker-publish:
          runner: butterfly
          badge-hook: https://hooks.microbadger.com/images/leodagan/butterfly/9Azpr64BRp0b1K7i-51ybdeoykI=
          <<: *images-publish-workflow
          requires:
            - latest
            - latest-arm32v6
            - latest-arm32v7
            - latest-arm64v8
            - edge
            - edge-arm32v6
            - edge-arm32v7
            - edge-arm64v8
