aria2-config:
  executor: &aria2-executor-defaults
    machine: true
    working_directory: ~/docker

  environment: &aria2-env
    DOCKERFILE_PATH: Dockerfile
    DOCKER_REPO: leodagan/aria2

  attach_step: &aria2-attach-workspace
    attach_workspace:
      at: ~/
  persist_step: &aria2-persist-workspace
    persist_to_workspace:
      root: ~/
      paths:
        - docker

  build_cmd: &aria2-build-command cd aria2 && ./hooks/build
  save_cmd: &aria2-save-command cd aria2 && docker save -o "aria2-${DOCKER_TAG}.tar" "${DOCKER_REPO}:${DOCKER_TAG}"
  load_cmd: &aria2-load-command cd aria2 && docker load < "aria2-${DOCKER_TAG}.tar"
  test_cmd: &aria2-test-command cd aria2 && ./hooks/test


version: 2

jobs:
  docker-checkout:
    <<: *aria2-executor-defaults
    steps:
      - *aria2-attach-workspace
      - checkout
      - *aria2-persist-workspace

  aria2-build-latest-amd64:
    <<: *aria2-executor-defaults
    steps:
      - *aria2-attach-workspace
      - run:
          name: aria2 amd64
          command: *aria2-build-command
          environment: &aria2-env-amd64
            <<: *aria2-env
            DOCKER_TAG: latest
      - run:
          command: *aria2-save-command
          environment:
            <<: *aria2-env-amd64
      - run:
          command: cd aria2 && docker save -o "busybox.tar" "${DOCKER_REPO}:busybox"
          environment:
            <<: *aria2-env-amd64
      - *aria2-persist-workspace

  aria2-test-latest-amd64:
    <<: *aria2-executor-defaults
    steps:
      - *aria2-attach-workspace
      - run:
          command: *aria2-load-command
          environment:
            <<: *aria2-env-amd64
      - run:
          command: cd aria2 && docker load < "busybox.tar"
          environment:
            <<: *aria2-env-amd64
      - run:
          name: test aria2 amd64
          command: *aria2-test-command
          environment:
            <<: *aria2-env-amd64

  aria2-build-latest-arm32v7:
    <<: *aria2-executor-defaults
    steps:
      - *aria2-attach-workspace
      - run:
          name: aria2 arm32v7
          command: *aria2-build-command
          environment: &aria2-env-arm32v7
            <<: *aria2-env
            DOCKER_TAG: latest-arm32v7
      - run:
          command: *aria2-save-command
          environment:
            <<: *aria2-env-arm32v7
      - run:
          command: cd aria2 && docker save -o "busybox-arm32v7.tar" "${DOCKER_REPO}:busybox-arm32v7"
          environment:
            <<: *aria2-env-arm32v7
      - *aria2-persist-workspace

  aria2-test-latest-arm32v7:
    <<: *aria2-executor-defaults
    steps:
      - *aria2-attach-workspace
      - run:
          command: *aria2-load-command
          environment:
            <<: *aria2-env-arm32v7
      - run:
          command: cd aria2 && docker load < "busybox-arm32v7.tar"
          environment:
            <<: *aria2-env-arm32v7
      - run:
          name: test aria2 arm32v7
          command: *aria2-test-command
          environment:
            <<: *aria2-env-arm32v7


workflows:
  version: 2
  aria2-latest:
    jobs:
      - docker-checkout
      - aria2-build-latest-amd64:
          requires:
            - docker-checkout
      - aria2-test-latest-amd64:
          requires:
            - aria2-build-latest-amd64
      - aria2-build-latest-arm32v7:
          requires:
            - docker-checkout
      - aria2-test-latest-arm32v7:
          requires:
            - aria2-build-latest-arm32v7

