#!/usr/bin/env sh

set -x

. "$(dirname "$0")/versions"
. "$(dirname "$0")/../../scripts/global_functions.sh"

if [ "${DO_NOTHING}" = "true" ]; then
    echo "Not doing anything because DO_NOTHING flag is set to true"
    exit 0
fi

DOCKER_ARCH="$(docker_tag_to_docker_arch "${DOCKER_TAG}")"

prepare_dockerfile_qemu "${DOCKERFILE_PATH}" "${DOCKER_ARCH}"

build()
{
    build_docker_image \
        --file "${DOCKERFILE_PATH}.${DOCKER_ARCH}" \
        --target final \
        "$@" \
}

case "${DOCKER_TAG}" in
    *-arm32v7)
        sed -i -e "s/arm32v7\/nginx:alpine/arm32v7\/nginx:latest/g" "${DOCKERFILE_PATH}.${DOCKER_ARCH}"
    ;;
esac

case "${DOCKER_TAG}" in
    latest)
        build \
            --build-arg ariang_version="tags/${ARIANG_REF_VERSION}" \
            --build-arg BUILD_VERSION="${ARIANG_REF_VERSION}-rc${ARIANG_IMAGE_VERSION}" \
            --tag "${DOCKER_REPO}:${DOCKER_TAG}"  --tag "${DOCKER_REPO}:${ARIANG_REF_VERSION}"
    ;;
    latest-*)
        build \
            --build-arg ariang_version="tags/${ARIANG_REF_VERSION}" \
            --build-arg BUILD_VERSION="${ARIANG_REF_VERSION}-rc${ARIANG_IMAGE_VERSION}" \
            --tag "${DOCKER_REPO}:${DOCKER_TAG}"  --tag "${DOCKER_REPO}:${ARIANG_REF_VERSION}-${DOCKER_ARCH}"
    ;;
    edge*)
        build \
            --build-arg ariang_version="master" \
            --build-arg BUILD_VERSION="$(git ls-remote https://github.com/mayswind/AriaNg.git master | head -1 | cut -f1)-rc${ARIANG_IMAGE_VERSION}" \
            --tag "${DOCKER_REPO}:${DOCKER_TAG}"
    ;;
    *)
        echo "Unsupported Docker Tag : ${DOCKER_TAG}"
        exit 1
    ;;
esac

