#!/usr/bin/env sh

set -x

prepare()
{
    if [ "${DOCKER_ARCH}x" = "x" ] || [ "${DOCKER_ARCH}" = "amd64" ]; then
        sed \
            -e "s/__DOCKER_ARCH__/amd64/g" \
            -e "/__QEMU_ARCH__/d" \
            "${DOCKERFILE_PATH}" > "${DOCKERFILE_PATH}.${DOCKER_ARCH}"
    else
        QEMU_USER_STATIC_DOWNLOAD_URL="https://github.com/multiarch/qemu-user-static/releases/download"
        QEMU_USER_STATIC_LATEST_TAG=$(curl -sL https://api.github.com/repos/multiarch/qemu-user-static/tags \
            | grep 'name.*v[0-9]' \
            | head -n 1 \
            | cut -d '"' -f 4)

        curl -sL "${QEMU_USER_STATIC_DOWNLOAD_URL}/${QEMU_USER_STATIC_LATEST_TAG}/x86_64_qemu-${QEMU_ARCH}-static.tar.gz" \
            | tar xzv

        sed \
            -e "s/__DOCKER_ARCH__/${DOCKER_ARCH}/g" \
            -e "s/__QEMU_ARCH__/${QEMU_ARCH}/g" \
            "${DOCKERFILE_PATH}" > "${DOCKERFILE_PATH}.${DOCKER_ARCH}"

        docker run --rm --privileged multiarch/qemu-user-static:register --reset
    fi
}

build_final()
{
    docker build \
        --file "${DOCKERFILE_PATH}.${DOCKER_ARCH}" \
        --build-arg ariang_version="${ARIANG_VERSION}" \
        --build-arg BUILD_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ") \
        --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
        --build-arg BUILD_VERSION="${LABEL_VERSION}" \
        --target final \
        "$@" \
        .
}

case "${DOCKER_TAG}" in
    'latest')
        ARIANG_VERSION='tags/1.1.1'
        DOCKER_ARCH='amd64'
        LABEL_VERSION='1.1.1-rc1'
        prepare
        build_final --tag "${DOCKER_REPO}:${DOCKER_TAG}" --tag "${DOCKER_REPO}:1.1.1"
        ;;
    'latest-arm32v6')
        ARIANG_VERSION='tags/1.1.1'
        DOCKER_ARCH='arm32v6'
        QEMU_ARCH='arm'
        LABEL_VERSION='1.1.1-rc1'
        prepare
        build_final --tag "${DOCKER_REPO}:${DOCKER_TAG}" --tag "${DOCKER_REPO}:1.1.1-arm32v6"
        ;;
    'latest-arm32v7')
        ARIANG_VERSION='tags/1.1.1'
        DOCKER_ARCH='arm32v7'
        QEMU_ARCH='arm'
        LABEL_VERSION='1.1.1-rc1'
        prepare
        sed -i -e "s/arm32v7\/nginx:alpine/arm32v7\/nginx:latest/g" "${DOCKERFILE_PATH}.${DOCKER_ARCH}"
        build_final --tag "${DOCKER_REPO}:${DOCKER_TAG}" --tag "${DOCKER_REPO}:1.1.1-arm32v7"
        ;;
     'latest-arm64v8')
        ARIANG_VERSION='tags/1.1.1'
        DOCKER_ARCH='arm64v8'
        QEMU_ARCH='aarch64'
        LABEL_VERSION='1.1.1-rc1'
        prepare
        build_final --tag "${DOCKER_REPO}:${DOCKER_TAG}" --tag "${DOCKER_REPO}:1.1.1-arm64v8"
        ;;
     'edge')
        ARIANG_VERSION='master'
        DOCKER_ARCH='amd64'
        LABEL_VERSION="$(git ls-remote https://github.com/mayswind/AriaNg.git "${ARIANG_VERSION}" | head -1 | cut -f1)-rc1"
        prepare
        build_final --tag "${DOCKER_REPO}:${DOCKER_TAG}"
        ;;
    'edge-arm32v6')
        ARIANG_VERSION='master'
        DOCKER_ARCH='arm32v6'
        QEMU_ARCH='arm'
        LABEL_VERSION="$(git ls-remote https://github.com/mayswind/AriaNg.git "${ARIANG_VERSION}" | head -1 | cut -f1)-rc1"
        prepare
        build_final --tag "${DOCKER_REPO}:${DOCKER_TAG}"
        ;;
    'edge-arm32v7')
        ARIANG_VERSION='master'
        DOCKER_ARCH='arm32v7'
        QEMU_ARCH='arm'
        LABEL_VERSION="$(git ls-remote https://github.com/mayswind/AriaNg.git "${ARIANG_VERSION}" | head -1 | cut -f1)-rc1"
        prepare
        sed -i -e "s/arm32v7\/nginx:alpine/arm32v7\/nginx:latest/g" "${DOCKERFILE_PATH}.${DOCKER_ARCH}"
        build_final --tag "${DOCKER_REPO}:${DOCKER_TAG}"
        ;;
    'edge-arm64v8')
        ARIANG_VERSION='master'
        DOCKER_ARCH='arm64v8'
        QEMU_ARCH='aarch64'
        LABEL_VERSION="$(git ls-remote https://github.com/mayswind/AriaNg.git "${ARIANG_VERSION}" | head -1 | cut -f1)-rc1"
        prepare
        build_final --tag "${DOCKER_REPO}:${DOCKER_TAG}"
        ;;
    *)
        echo "Unsupported Docker Tag : ${DOCKER_TAG}"
        exit 1
        ;;
esac

