#!/usr/bin/env sh

set -x

. "$(dirname "$0")/../../scripts/global_functions.sh"

if [ "${DO_NOTHING}" = "true" ]; then
    echo "Not doing anything because DO_NOTHING flag is set to true"
    exit 0
fi

qemu_test "${DOCKER_REPO}:${DOCKER_TAG}" --help
